### ISSUE TITLE
[Bug]:  As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.

### ISSUE THREAD

**Issue by xmlking** [sveltinio/sveltin#153]
<img width="1055" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/8ed5979b-ce49-4bae-ab5e-8e50e441dce2">

**Comment by indaco** [comment]
@xmlking thanks for reporting it. Will be fixed by the upcoming patch release
