### ISSUE TITLE
[Bug]: build failed after upgrading @sveltinio/widgets 

### ISSUE THREAD

**Issue by xmlking** [sveltinio/sveltin#157]
as discussed here https://github.com/sveltinio/sveltin/issues/154

Build error : Error: 404 /posts/undefined/ (linked from /posts/undefined)

It worked till "@sveltinio/widgets": "0.7.4" looks like this issue is introduced in maybe in  0.7.5/0.7.6 version

Environment:
all latest versions except   `remark-reading-time` downgrade to `v1.0.1`

Reproduce 
https://github.com/xmlking/spectacular/tree/main/apps/docs

**Comment by indaco** [comment]
@xmlking Thanks for reporting this 

Does your IDE highligh any error on routes/posts/+page.svelte or /routes/posts/+page.ts files?

Will check asap 

Thanks

**Comment by xmlking** [comment]
I see only following red highlight 
<img width="1106" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/c714424f-c998-4bd6-b018-d178b0a0bbb9">

<img width="393" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/a0af2c19-ae51-402c-8447-ac7648528e39">


appreciate  your quick responce.

**Comment by indaco** [comment]
The screenshot refers to /routes/+page.svelte

I was asking for one from /routes/posts/

**Comment by xmlking** [comment]
> The screenshot refers to /routes/+page.svelte
> 
> I was asking to one from /routes/posts/

updated

**Comment by xmlking** [comment]
<img width="992" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/19ffc915-f5e2-473f-9659-a1423ffae195">
<img width="717" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/d0e7e921-c210-45c6-8625-58cfeee6b24d">

**Comment by indaco** [comment]
@xmlking 
I think to have identified the issue.

It happens due to an error in the `PagesNavigator` component within `/routes/posts/[slug]/+page.svelte`

Will fix `@sveltinio/widgets` on tomorrow, mean while you can wrap the `PagesNavigator` component with a `{#if ...}` like the following

```
{#if previous.metadata.slug && next.metadata.slug}
	<PagesNavigator
		prev={{
			label: previous.metadata.title,
			href: `${base}/${previous.resource}/${previous.metadata.slug}`,
			title: `link to ${previous.metadata.title}`
		}}
		next={{
			label: next.metadata.title,
			href: `${base}/${next.resource}/${next.metadata.slug}`,
			title: `link to ${next.metadata.title}`
		}}
	/>
{/if}
```

let me know. Thanks

**Comment by xmlking** [comment]
I can upgrade @sveltinio/widgets to latest with above workaround

**Comment by indaco** [comment]
Yes, that temporary workaround allows you to upgrade to the latest version of widgets. 

Keep you posted once I fixed it and released 

Thanks

**Comment by indaco** [comment]
@xmlking can you check now upgrading `@sveltinio/widgets` to the latest `0.7.9` version and removing the previous workaround? Thanks

**Comment by xmlking** [comment]
tested without workaround. it is working 👍🏽
